View list of items
franzsalvador/jamazon pull request #7
Opened 2018-06-28 20:27 UTC by FranzCSUF

![jam](https://user-images.githubusercontent.com/39274811/42059014-f728e622-7ad6-11e8-8fb5-0bcf0bc7d33a.gif)

2018-06-28 21:06 UTC, thebearingedge requested changes

2018-06-28 21:06 UTC, thebearingedge commented on styles.css
> +  /* border: 2px solid blue; */
Please omit commented code from your Pull Requests.

2018-06-28 21:06 UTC, thebearingedge commented on main.js
> +function buildCatalog() {
This `buildCatalog` should be a "pure function" just like your `displayItem` function. It should take the whole items list as a parameter and return a DOM tree without actually putting it in the page.

2018-06-28 21:06 UTC, thebearingedge commented on main.js
> +/* eslint-disable no-unused-vars */
You can remove this now.

2018-06-28 21:06 UTC, thebearingedge commented on main.js
> +function displayItem(itemNumber) {
Instead of defining your function to take an index or number, assume you'll be passing it a whole item object from your catalog array.

2018-06-28 21:06 UTC, thebearingedge commented on main.js
> +function renderCatalog() {
`renderCatalog` should be named something like `renderApp` and it should take the whole `app` as its argument.
Then get the items from the catalog and build the `$catalog` with your "pure" `buildCatalog` function. At that point you can append the built catalog to the `data-view="catalog"` in `index.html`.

2018-06-29 16:40 UTC, thebearingedge requested changes
YES!! Just add one line at the bottom that calls your `renderApp` function so the user doesn't have to 😄 .

2018-06-29 16:53 UTC, merged

2018-06-29 16:53 UTC, FranzCSUF commented
Pull request approved.